---
label-mode: segmentation
in_path: "C:/Users/alist/Documents/Projects/iris/demo/data"
image_filename: "image.npy"
out_path: "C:/Users/alist/Documents/Projects/iris/demo/out"
first_guess_available: False
classes:
- name: Clear
  description: All clear pixels, i.e. without cloud contamination or cloud shadows.
  colour:
  - 255
  - 255
  - 255
  - 0
  user_colour:
  - 0
  - 255
  - 255
  - 70
- name: Cloud
  description: All cloudy pixels covered by clouds.
  colour:
  - 255
  - 255
  - 0
  - 70
- name: Cloud Shadows
  description: All pixels contaminated by cloud shadows (not terrain shadows).
  colour:
  - 255
  - 0
  - 0
  - 70
image_shape:
- 512
- 512
# If you want to allow the users only to label a subset of the tile:
mask_area:
- 64
- 64
- 448
- 448
views:
- name: Cirrus
  description: In this band combination vegetation appears in shades of red, soils
    vary from dark to light brown and urban areas are cyan blue. Snow, ice, and clouds
    are <b>light cyan or white</b>.
  channels:
  - (B11*70)
  - (B11*70)
  - (B11*70)
- name: RGB
  description: Normal RGB image.
  channels:
  - B5
  - B3
  - B2
- name: Snow vs. Clouds
  description: Small ice crystals in high-level clouds appear reddish-orange or peach,
    and thick ice snow looks vivid red (or red-orange). Bare soil appears bright cyan
    and vegetation seem greenish in the image. Water on the ground is very dark as
    it absorbs the SWIR and the red, but small (liquid) water drops in the clouds
    scatter the light equally in both visible and the SWIR, and therefore it appears
    white. Water Sediments are displayed as dark red.
  channels:
  - B1
  - B12
  - B13
